In basemodel.ipynb "NameError" exists. Workaround: Copy whole code into an IDE like Pycharm and run ! 
